### ISSUE TITLE
npm start fails 

### ISSUE THREAD

**Issue by rohan-paul** [mathieupoterie/socialnetwork-react#2]
After running ``npm start`` getting the below error 

 ```
react-setup@1.0.0 start /home/paul/PAUL/H/Web/R/R-Vid/2018/mern-stack-front-to-back-DEVELOPER-SOCIAL-NETWORK/OTHER-GIT-CLONED/socialnetwork-react
> npm run build && node index.js


> react-setup@1.0.0 build /home/paul/PAUL/H/Web/R/R-Vid/2018/mern-stack-front-to-back-DEVELOPER-SOCIAL-NETWORK/OTHER-GIT-CLONED/socialnetwork-react
> node build.js

internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module '../secrets'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/paul/PAUL/H/Web/R/R-Vid/2018/mern-stack-front-to-back-DEVELOPER-SOCIAL-NETWORK/OTHER-GIT-CLONED/socialnetwork-react/config/s3.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)

```

**Comment by Davidmenamm** [comment]
I have the same issue when installing.
